# folder settings
source: .
destination: ./_site

# site settings
permalink: /:title

# site url
url: http://zv.github.io

# Me
full-name: Zephyr Pellerin
title: A new kind of sentience
email: zv@nxvr.org
author:
  name: Zephyr Pellerin 
  email: zv@nxvr.org
  uri: https://zv.github.io/about

# Site name
name: zv's blog
description: zv's blog

# Site settings
baseurl: "" 
twitter_username: zefyear
github_username: zv

sass:
  sass_dir: _sass
  style: compressed

# exclude files for generated site
exclude: 
  - org/
  - LICENSE
  - node_modules
  - package.json